on:
  push:
    branches:
      - master

name: Build and Publish
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          # ↓ This is really important apparently
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Bump package version
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const packageJson = require('./package.json');
            const npmRegistryUrl = 'https://registry.npmjs.org';

            const currentPackageVersion = await fetch(`${npmRegistryUrl}/${packageJson.name}/latest`).then(async (res) => (await res.json()).version);

            const commitMessage = context.payload.head_commit.message;
            let [major, minor, patch] = currentPackageVersion.split('.').map(v => parseInt(v, 10));
            if (commitMessage.includes('BREAKING CHANGE') || commitMessage.includes('!:')) {
              major++;
              minor = 0;
              patch = 0;
            } else if (commitMessage.toLowerCase().startsWith('feat')) {
              minor++;
              patch = 0;
            } else {
              patch++;
            }
            const newPackageVersion = `${major}.${minor}.${patch}`;

            exec.exec(`npm version ${newPackageVersion} --no-git-tag-version --allow-same-version`);
      - name: Build
        run: npm run build

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
          npm publish
          git checkout package.json
